### ISSUE TITLE
[Feature request] Add SIMD operations support

### ISSUE THREAD

**Issue by hwalker928** [sparkedhost/images#4]
Pufferfish (and other forks, e.g. Purpur), recommend that the flag `--add-modules=jdk.incubator.vector` is added to the startup command to enable SIMD operations, which according to the message below, optimises the server.

```
[Pufferfish] SIMD operations are available for your server, but are not configured!
[Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[Pufferfish] Debug: Java: 18.0.2.1, test run: true
```

As a result, having an option like the Log4J workaround and Forge Compatibility would be a suitable option here. Every server that I have tried this on (which is a fair few) has worked as is supported by the JVM and the CPU.

**Comment by BetTD** [comment]
Have you tested this on different CPUs and categories (Budget, Enterprise, Extreme)? I'm mainly worried about Budget, theoretically, most CPUs should have some SIMD capabilities, just not sure if Pufferfish will like those.

**Comment by hwalker928** [comment]
Yes, @BetTD, I have tested this on some of our Budget hardware, however, it will be disabled by default anyways, so if it doesn't work for a server then it doesn't work.

**Comment by BetTD** [comment]
Green light then
