### ISSUE TITLE
Servers using -Xmx()G cannot use Startup changes

### ISSUE THREAD

**Issue by hwalker928** [sparkedhost/images#6]
**Describe the bug**
If a server uses a manual RAM amount with `G` and the Java images, e.g. `-Xmx4G`, then Startup changes, e.g. Log4J & Aikar's Flags, are not applied.

**To Reproduce**
1. Use a `java-jre` image.
2. Set a server to use `-Xmx2G` manually.
3. See that any Startup changes are not present on the server.

**Expected behavior**
Startup parameters still apply.

**Comment by BetTD** [comment]
Under what circumstances would a server have a custom -Xmx value in gigabytes (G)?
