### ISSUE TITLE
Deprecating Python 3.6 and 3.7

### ISSUE THREAD

**Issue by hwalker928** [sparkedhost/images#7]
As noted [here](https://endoflife.date/python), Python 3.6 has been EOL for over a year ago now, and Python 3.7 is not supported by the `discord.py` library and becomes EOL in 5 months.

Therefore we could do something similar to #2 and https://github.com/sparkedhost/images/commit/f890f4a070da67a6d9b74c118c0f68925c6d3c18 where the weekly schedule is removed.

**Comment by BetTD** [comment]
Node.js images will have their build schedule reinstated but changed to monthly, as there are still some apt packages in those that could potentially receive updates. I suggest we do the same for Python 3.6, and we'll do 3.7 later when it actually becomes EOL. We should follow the Python release lifecycle, not discord.py's.
