### ISSUE TITLE
Support for deploy-commands.js on Startup

### ISSUE THREAD

**Issue by hwalker928** [sparkedhost/images#9]
Add a startup variable which appends `node deploy-commands.js` after npm installation to the startup command.

**Comment by 0x7d8** [comment]
Shouldnt the user do that himself?
I mean it requires a simple
```js
require('./deploy-commands')
```
as the first line of the index.js file, done

also works with esm
```js
import "./deploy-commands.js"
```

**Comment by hwalker928** [comment]
@rotvproHD Agreed. Will close this issue in favour of that.
